/*
 * This file is generated by jOOQ.
 */
package com.gruelbox.asyncalltheway.integration.jooq.public_;


import com.gruelbox.asyncalltheway.integration.jooq.public_.tables.Stuff;
import com.gruelbox.asyncalltheway.integration.jooq.public_.tables.records.StuffRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<StuffRecord> CONSTRAINT_4 = UniqueKeys0.CONSTRAINT_4;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<StuffRecord> CONSTRAINT_4 = Internal.createUniqueKey(Stuff.STUFF, "CONSTRAINT_4", new TableField[] { Stuff.STUFF.ID }, true);
    }
}
