/*
 * This file is generated by jOOQ.
 */
package com.gruelbox.asyncalltheway.integration.jooq.public_;


import com.gruelbox.asyncalltheway.integration.jooq.DefaultCatalog;
import com.gruelbox.asyncalltheway.integration.jooq.public_.tables.Stuff;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1806796389;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.STUFF</code>.
     */
    public final Stuff STUFF = Stuff.STUFF;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Stuff.STUFF);
    }
}
