/*
 * This file is generated by jOOQ.
 */
package com.gruelbox.asyncalltheway.integration.jooq.public_;


import com.gruelbox.asyncalltheway.integration.jooq.public_.tables.Stuff;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.STUFF</code>.
     */
    public static final Stuff STUFF = Stuff.STUFF;
}
