/*
 * This file is generated by jOOQ.
 */
package com.gruelbox.asyncalltheway.integration.jooq.public_.tables.pojos;


import com.gruelbox.asyncalltheway.integration.jooq.public_.tables.interfaces.IStuff;

import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Stuff implements VertxPojo, IStuff {

    private static final long serialVersionUID = -2098606977;

    private String id;
    private String data;
    private Long   version;

    public Stuff() {}

    public Stuff(IStuff value) {
        this.id = value.getId();
        this.data = value.getData();
        this.version = value.getVersion();
    }

    public Stuff(
        String id,
        String data,
        Long   version
    ) {
        this.id = id;
        this.data = data;
        this.version = version;
    }

    @Override
    public String getId() {
        return this.id;
    }

    @Override
    public Stuff setId(String id) {
        this.id = id;
        return this;
    }

    @Override
    public String getData() {
        return this.data;
    }

    @Override
    public Stuff setData(String data) {
        this.data = data;
        return this;
    }

    @Override
    public Long getVersion() {
        return this.version;
    }

    @Override
    public Stuff setVersion(Long version) {
        this.version = version;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Stuff (");

        sb.append(id);
        sb.append(", ").append(data);
        sb.append(", ").append(version);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IStuff from) {
        setId(from.getId());
        setData(from.getData());
        setVersion(from.getVersion());
    }

    @Override
    public <E extends IStuff> E into(E into) {
        into.from(this);
        return into;
    }

    public Stuff(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
