/*
 * This file is generated by jOOQ.
 */
package com.gruelbox.asyncalltheway.integration.jooq.public_.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IStuff extends VertxPojo, Serializable {

    /**
     * Setter for <code>public.STUFF.ID</code>.
     */
    public IStuff setId(String value);

    /**
     * Getter for <code>public.STUFF.ID</code>.
     */
    public String getId();

    /**
     * Setter for <code>public.STUFF.DATA</code>.
     */
    public IStuff setData(String value);

    /**
     * Getter for <code>public.STUFF.DATA</code>.
     */
    public String getData();

    /**
     * Setter for <code>public.STUFF.VERSION</code>.
     */
    public IStuff setVersion(Long value);

    /**
     * Getter for <code>public.STUFF.VERSION</code>.
     */
    public Long getVersion();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IStuff
     */
    public void from(IStuff from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IStuff
     */
    public <E extends IStuff> E into(E into);

    @Override
    public default IStuff fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setId(json.getString("ID"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("ID","java.lang.String",e);
        }
        try {
            setData(json.getString("DATA"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("DATA","java.lang.String",e);
        }
        try {
            setVersion(json.getLong("VERSION"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("VERSION","java.lang.Long",e);
        }
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("ID",getId());
        json.put("DATA",getData());
        json.put("VERSION",getVersion());
        return json;
    }

}
