/*
 * This file is generated by jOOQ.
 */
package com.gruelbox.asyncalltheway.integration.jooq.public_.tables.daos;


import com.gruelbox.asyncalltheway.integration.jooq.public_.tables.Stuff;
import com.gruelbox.asyncalltheway.integration.jooq.public_.tables.records.StuffRecord;

import io.github.jklingsporn.vertx.jooq.shared.async.AbstractAsyncVertxDAO;

import java.util.Collection;

import org.jooq.Configuration;


import java.util.List;
import io.reactivex.Single;
import java.util.Optional;
import io.github.jklingsporn.vertx.jooq.rx.async.AsyncRXQueryExecutor;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@javax.inject.Singleton
public class StuffDao extends AbstractAsyncVertxDAO<StuffRecord, com.gruelbox.asyncalltheway.integration.jooq.public_.tables.pojos.Stuff, String, Single<List<com.gruelbox.asyncalltheway.integration.jooq.public_.tables.pojos.Stuff>>, Single<Optional<com.gruelbox.asyncalltheway.integration.jooq.public_.tables.pojos.Stuff>>, Single<Integer>, Single<String>> implements io.github.jklingsporn.vertx.jooq.rx.VertxDAO<StuffRecord,com.gruelbox.asyncalltheway.integration.jooq.public_.tables.pojos.Stuff,String> {
    @javax.inject.Inject

    /**
     * @param configuration Used for rendering, so only SQLDialect must be set and must be one of the MYSQL types or POSTGRES.
     * @param delegate A configured AsyncSQLClient that is used for query execution
     */
    public StuffDao(Configuration configuration,io.vertx.reactivex.ext.asyncsql.AsyncSQLClient delegate) {
        super(Stuff.STUFF, com.gruelbox.asyncalltheway.integration.jooq.public_.tables.pojos.Stuff.class, new AsyncRXQueryExecutor<StuffRecord,com.gruelbox.asyncalltheway.integration.jooq.public_.tables.pojos.Stuff,String>(configuration,delegate,com.gruelbox.asyncalltheway.integration.jooq.public_.tables.pojos.Stuff::new, Stuff.STUFF));
    }

    @Override
    protected String getId(com.gruelbox.asyncalltheway.integration.jooq.public_.tables.pojos.Stuff object) {
        return object.getId();
    }

    /**
     * Find records that have <code>DATA IN (values)</code> asynchronously
     */
    public Single<List<com.gruelbox.asyncalltheway.integration.jooq.public_.tables.pojos.Stuff>> findManyByData(Collection<String> values) {
        return findManyByCondition(Stuff.STUFF.DATA.in(values));
    }

    /**
     * Find records that have <code>VERSION IN (values)</code> asynchronously
     */
    public Single<List<com.gruelbox.asyncalltheway.integration.jooq.public_.tables.pojos.Stuff>> findManyByVersion(Collection<Long> values) {
        return findManyByCondition(Stuff.STUFF.VERSION.in(values));
    }

    @Override
    public AsyncRXQueryExecutor<StuffRecord,com.gruelbox.asyncalltheway.integration.jooq.public_.tables.pojos.Stuff,String> queryExecutor(){
        return (AsyncRXQueryExecutor<StuffRecord,com.gruelbox.asyncalltheway.integration.jooq.public_.tables.pojos.Stuff,String>) super.queryExecutor();
    }
}
