/*
 * This file is generated by jOOQ.
 */
package com.gruelbox.asyncalltheway.integration.jooq.public_.tables;


import com.gruelbox.asyncalltheway.integration.jooq.public_.Keys;
import com.gruelbox.asyncalltheway.integration.jooq.public_.Public;
import com.gruelbox.asyncalltheway.integration.jooq.public_.tables.records.StuffRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Stuff extends TableImpl<StuffRecord> {

    private static final long serialVersionUID = -2105985597;

    /**
     * The reference instance of <code>public.STUFF</code>
     */
    public static final Stuff STUFF = new Stuff();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StuffRecord> getRecordType() {
        return StuffRecord.class;
    }

    /**
     * The column <code>public.STUFF.ID</code>.
     */
    public final TableField<StuffRecord, String> ID = createField(DSL.name("ID"), org.jooq.impl.SQLDataType.VARCHAR(34).nullable(false), this, "");

    /**
     * The column <code>public.STUFF.DATA</code>.
     */
    public final TableField<StuffRecord, String> DATA = createField(DSL.name("DATA"), org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.STUFF.VERSION</code>.
     */
    public final TableField<StuffRecord, Long> VERSION = createField(DSL.name("VERSION"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>public.STUFF</code> table reference
     */
    public Stuff() {
        this(DSL.name("STUFF"), null);
    }

    /**
     * Create an aliased <code>public.STUFF</code> table reference
     */
    public Stuff(String alias) {
        this(DSL.name(alias), STUFF);
    }

    /**
     * Create an aliased <code>public.STUFF</code> table reference
     */
    public Stuff(Name alias) {
        this(alias, STUFF);
    }

    private Stuff(Name alias, Table<StuffRecord> aliased) {
        this(alias, aliased, null);
    }

    private Stuff(Name alias, Table<StuffRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Stuff(Table<O> child, ForeignKey<O, StuffRecord> key) {
        super(child, key, STUFF);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<StuffRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_4;
    }

    @Override
    public List<UniqueKey<StuffRecord>> getKeys() {
        return Arrays.<UniqueKey<StuffRecord>>asList(Keys.CONSTRAINT_4);
    }

    @Override
    public TableField<StuffRecord, Long> getRecordVersion() {
        return VERSION;
    }

    @Override
    public Stuff as(String alias) {
        return new Stuff(DSL.name(alias), this);
    }

    @Override
    public Stuff as(Name alias) {
        return new Stuff(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Stuff rename(String name) {
        return new Stuff(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Stuff rename(Name name) {
        return new Stuff(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
