/*
 * This file is generated by jOOQ.
 */
package com.gruelbox.asyncalltheway.persistence.jooq;


import com.gruelbox.asyncalltheway.persistence.jooq.tables.Stuff;


/**
 * Convenience access to all tables in 
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>STUFF</code>.
     */
    public static final Stuff STUFF = Stuff.STUFF;
}
